:sparkles: add support for Ethereum
rated-network/rated-python pull request #1
Opened 2024-02-07 09:39 UTC by menecio

### Context
This PR adds support for the Ethereum network in the RatedAPI.

The proposal is that it should be used like this:
```python
import rated
from rated.networks import Ethereum

r = rated.Rated("ey...")
eth = r.ethereum(Ethereum.Mainnet)
for eff in eth.validator.effectiveness("0x123456789...", from_day=873, size=1): 
    print(f"Day: {eff.day}, Eff: {eff.validator_effectiveness}")

>>> Day: 873, Eff: 98.82005899705014
>>> Day: 872, Eff: 98.83015896502001
>>> ...
```

2024-02-07 09:53 UTC, haiyanghe approved these changes

2024-02-07 09:53 UTC, haiyanghe commented on src/rated/ethereum/datatypes.py
> +@dataclass
Are we using dataclasses instead of Pydantic models in this library?

2024-02-07 10:30 UTC, menecio commented on src/rated/ethereum/datatypes.py
> +@dataclass
We could use pydantic but it doesn't really add much other than having identical classes to the ones we already use. 

But if we think we should use pydantic, I don't have a strong opinion against it.

2024-02-07 11:26 UTC, ariskk commented on README.md
> +r = rated.Rated("ey...")
Some definition of what `ey...` is and how to get it (short description, point to console etc).

2024-02-07 11:28 UTC, ariskk commented on src/rated/__init__.py
> +        self.api_key = api_key_ or api_key
if this is empty, there is no meaningful way to progress. So I guess better if we raise the `ValueError` here?

2024-02-07 11:32 UTC, ariskk commented on src/rated/ethereum/datatypes.py
> +@dataclass
Slight preference for pydantic given the types are a bit more descriptive (eg `NonNegativeInt` vs just `int`)
What do you think @JavierHuertaGarces ?

2024-02-07 11:34 UTC, ariskk commented on src/rated/ethereum/datatypes.py
> +    end_epoch: Optional[int]
Something interesting we could do here is attach methods that thematically returns subsets. eg we could have a class for `ValidatorRewards` and then have the ability to do `effectiveness.rewards()`

2024-02-07 11:36 UTC, ariskk commented on src/rated/ethereum/validators.py
> +    def metadata(self, index_or_pubkey: int | str) -> ValidatorMetadata:
we should def have some validation here (can be pydantic or something else) to verify that  `index_or_pubkey` is either a `NonNegativeInt` or a 96/98 character long hex. That is to avoid sending to the API a request we know will fail.

2024-02-07 11:38 UTC, ariskk commented on src/rated/ethereum/validators.py
> +        time_window: str = "1d",
Would be good to validate this before sending and raise a ValueError with the valid options

2024-02-07 11:39 UTC, ariskk commented on src/rated/client.py
>      def get(self, *args, **kwargs) -> httpx.Response:
I wonder if a `stamina` config would be useful here

2024-02-07 11:40 UTC, ariskk commented on src/rated/ethereum/validators.py
> +            effectiveness = self.client.get(url, params=params)
since we do `effectinveness.json()` three times, maybe assign it to a variable.

2024-02-07 11:41 UTC, ariskk commented on src/rated/ethereum/validators.py
> +        while True:
this will get all the data all the way to genesis, regardless of the `size` the user has submitted. Is that intended?

2024-02-07 11:56 UTC, JavierHuertaGarces commented on src/rated/__init__.py
> +    def ethereum(self, network: Ethereum) -> ethereum.Ethereum:
I'm not a fan of the network Enum and the actual network client sharing a name. There are a lot of `ethereum` and `Ethereum` around in packages, classes and types, which can make the code a bit hard to follow. Maybe we could be more specific in the naming.

2024-02-07 11:57 UTC, JavierHuertaGarces commented on src/rated/base.py
> +    def client(self) -> Client:
Not sure if this is a pattern we are purposely following, but why make the property within the `__init__` private if you are going to expose it here anyway?

2024-02-07 12:01 UTC, JavierHuertaGarces commented on src/rated/client.py
>          self.api_key = os.getenv("RATED_API_KEY", api_key)
We should probably get rid of this here, as we already get the `RATED_API_KEY` before we call the client. Same thing with the `api_key` validation. I'd probably keep it in one place. If, for some reason, we want to keep it in both places, then I'd declare the env variable name somewhere to not repeat the string value.

2024-02-07 12:19 UTC, menecio commented on src/rated/__init__.py
> +        self.api_key = api_key_ or api_key
it will once you try to instantiate a network, which is when we init the `httpx.Client`

2024-02-07 12:20 UTC, menecio commented on src/rated/ethereum/validators.py
> +            effectiveness = self.client.get(url, params=params)
yup, there is some cleaning needed, def going to do that

2024-02-07 12:22 UTC, menecio commented on src/rated/ethereum/validators.py
> +        while True:
yes, so that you iterate over all pages by default. The use consuming would be responsible to stop iterating, 
e.g.
```python
for eff in eth.validator.effectiveness("0x123456789...", from_day=873, size=1): 
    if eff.day < 800:
        break
    print(f"Day: {eff.day}, Eff: {eff.validator_effectiveness}")
```
wdyt?

2024-02-07 12:27 UTC, JavierHuertaGarces commented on src/rated/ethereum/datatypes.py
> +@dataclass
My care factor for this is low, to be honest. I would say that unless we need to get that specific with types, I'd slightly favour dataclasses because you don't need an external dependency for them.

2024-02-07 12:49 UTC, JavierHuertaGarces commented on src/rated/__init__.py
> +    def ethereum(self, network: Ethereum) -> ethereum.Ethereum:
This might be a little out there, but what if you move the Ethereum network enum to the ethereum package? It's a bit more verbose, but everything comes from the same place, and packages from different networks would have their own `Network` enum. 

```python
import rated
from rated.ethereum import Network # It could also be aliased as EthNetwork for clarity

r = rated.Rated("ey...")

eth = r.ethereum(Network.Mainnet)
```

That also means that when creating the client:

```python
def ethereum(self, network: ethereum.Network) -> ethereum.Ethereum:
```

2024-02-07 13:05 UTC, JavierHuertaGarces commented on src/rated/__init__.py
> +    def ethereum(self, network: Ethereum) -> ethereum.Ethereum:
Also, we could change the enum values to uppercase so we don't confuse them with classes (something like https://docs.python.org/3/library/enum.html).

```python
import rated
from rated.ethereum import Network # It could also be aliased as EthNetwork for clarity

r = rated.Rated("ey...")

eth = r.ethereum(Network.MAINNET)
```

2024-02-07 17:10 UTC, ariskk commented on src/rated/ethereum/validators.py
> +        while True:
It seems counterintuitive. I wouldn't expect this to happen at all. I would expect to get one datapoint calling this `eth.validator.effectiveness("0x123456789...", from_day=873, size=1)`

2024-02-08 16:42 UTC, menecio commented on src/rated/ethereum/validators.py
> +        while True:
ok, I will add a `follow_next: bool = False` parameter, this will allow users to choose if they want to keep iterating if there is a next page

2024-02-09 08:48 UTC, ariskk commented on README.md
> +r = Rated("ey...")
Still needs a short guide how to obtain the key. Also better if we explicitly say what `"ey..."` is, ie `API_KEY = 'ey...'`

2024-02-12 10:56 UTC, ariskk commented on src/rated/ethereum/datatypes.py
> +    sum_externally_sourced_execution_rewards: Optional[int]
Not all of them are optional, would it better if this mirrored the API's models in terms of optionality

2024-02-15 10:41 UTC, menecio commented on src/rated/ethereum/slashings.py
> +    def for_validator(
what do you think about this naming? @rated-network/devs 

```python
import rated


r = rated.Rated("some_key")
eth = r.ethereum(network=rated.ethereum.MAINNET)

# by validator index
slashings = eth.slashings.for_validator(500_000)

# by pubkey
slashings = eth.slashings.for_validator("0x...")

for penalty in slashings:
    print(penalty)
```

2024-02-15 15:24 UTC, JavierHuertaGarces commented on src/rated/__init__.py
> +        if self.api_key is None:
I would switch this if around for readability:
```
if self.api_key:
    c = Client(api_key=self.api_key, network=network)
    return ethereum.Ethereum(c)

raise ValueError("Must provide an API key.")
```

2024-02-15 15:30 UTC, JavierHuertaGarces commented on src/rated/base.py
> +        if client.network not in self.supported_networks:
Would test for positive here as well.

2024-02-15 15:37 UTC, JavierHuertaGarces commented on src/rated/client.py
>          if not self.api_key:
Why do we recheck this? We already do in `class Rated:`

2024-02-15 16:21 UTC, JavierHuertaGarces requested changes

2024-02-15 16:21 UTC, JavierHuertaGarces commented on src/rated/base.py
> +    def get(self, *args, **kwargs) -> Any:
I find it a bit confusing having this here. I'd rather use the `get` in the client directly.

2024-02-15 16:21 UTC, JavierHuertaGarces commented on src/rated/ethereum/network.py
> +        stake_action: str = "activation",
Could we have enums for all API parameters that have a restricted set of values?

2024-02-15 16:21 UTC, JavierHuertaGarces commented on src/rated/ethereum/validators.py
> +    def metadata(self, index_or_pubkey: int | str) -> ValidatorMetadata:
Could we be more verbose and have 2 exclusive arguments? I think it will make validation easier to read, and the user can be more explicit in the function call.

2024-02-15 20:29 UTC, menecio commented on src/rated/client.py
> +            params_ = None
it comes embedded in the next url, so the params we carry from the previous requests are not useful anymore

2024-02-16 10:28 UTC, JavierHuertaGarces commented on src/rated/ethereum/enums.py
> +    NONE = None
Instead of having a `NONE` value for the enums that support it, couldn't we declare the arguments that use it as, in this case, `Granularity | None` instead?

2024-02-16 10:37 UTC, JavierHuertaGarces approved these changes

2024-02-16 10:40 UTC, menecio commented on src/rated/ethereum/enums.py
> +    NONE = None
it forces then to check `granularity.value if granularity is not None else None`, this way we can simply do granularity.value for any case

2024-02-16 11:13 UTC, merged